parameters:
#    ars_manager.example.class: ARS\ManagerBundle\Example

services:
#    ars_manager.example:
#        class: %ars_manager.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
